# Workflow name
name: Build
on:
# When it will be triggered
# And in which branch
  pull_request:
  push:
    branches:
      - master
# Where will they run
jobs:
  build:

    runs-on: ubuntu-latest
